version: '3.5'

services:

  pgadmin4:
      container_name: my_pgadmin4
      image: dpage/pgadmin4
      restart: "always"
      environment:
        PGADMIN_DEFAULT_EMAIL: "YOUR@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "PASSWORD"
        PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 365
        PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 60
      volumes:
        - pgadmin4-data:/var/lib/pgadmin
      ports:
        - "5050:80"
      extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
    pgadmin4-data:

# 更多的參數設定，文件可參考 https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html